// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/authelia/authelia/v4/internal/authentication (interfaces: LDAPClientFactory)

// Package authentication is a generated GoMock package.
package authentication

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLDAPClientFactory is a mock of LDAPClientFactory interface.
type MockLDAPClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockLDAPClientFactoryMockRecorder
}

// MockLDAPClientFactoryMockRecorder is the mock recorder for MockLDAPClientFactory.
type MockLDAPClientFactoryMockRecorder struct {
	mock *MockLDAPClientFactory
}

// NewMockLDAPClientFactory creates a new mock instance.
func NewMockLDAPClientFactory(ctrl *gomock.Controller) *MockLDAPClientFactory {
	mock := &MockLDAPClientFactory{ctrl: ctrl}
	mock.recorder = &MockLDAPClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLDAPClientFactory) EXPECT() *MockLDAPClientFactoryMockRecorder {
	return m.recorder
}

// Dial mocks base method.
func (m *MockLDAPClientFactory) Dial() (LDAPClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial")
	ret0, _ := ret[0].(LDAPClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockLDAPClientFactoryMockRecorder) Dial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockLDAPClientFactory)(nil).Dial))
}

// DialURL mocks base method.
func (m *MockLDAPClientFactory) DialURL(arg0 string) (LDAPClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialURL", arg0)
	ret0, _ := ret[0].(LDAPClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialURL indicates an expected call of DialURL.
func (mr *MockLDAPClientFactoryMockRecorder) DialURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialURL", reflect.TypeOf((*MockLDAPClientFactory)(nil).DialURL), arg0)
}
